k8s_yaml('caddy.yaml')
k8s_resource('caddy', port_forwards=6060)

docker_build('quay.io/signalcd/api', '../cmd/api')
k8s_yaml('../deployment/kubernetes/signalcd-api.yaml')
k8s_resource('signalcd-api', port_forwards=6660)

k8s_yaml('../deployment/kubernetes/signalcd-ui.yaml')
k8s_resource('signalcd-ui', port_forwards=6662)
docker_build('quay.io/signalcd/ui', '..', dockerfile='../cmd/ui/Dockerfile.dev',
  live_update=[sync('../ui/', '/app')]
)
