// Code generated by go-swagger; DO NOT EDIT.

package pipeline

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	models "github.com/signalcd/signalcd/api/v1/models"
)

// NewCreateParams creates a new CreateParams object
// no default values defined in spec.
func NewCreateParams() CreateParams {

	return CreateParams{}
}

// CreateParams contains all the bound params for the create operation
// typically these are obtained from a http.Request
//
// swagger:parameters create
type CreateParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*The pipeline to be created
	  In: body
	*/
	Pipeline *models.Pipeline
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewCreateParams() beforehand.
func (o *CreateParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.Pipeline
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			res = append(res, errors.NewParseError("pipeline", "body", "", err))
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Pipeline = &body
			}
		}
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
