// Code generated by go-swagger; DO NOT EDIT.

package pipeline

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/signalcd/signalcd/api/v1/models"
)

// PipelineAgentsOKCode is the HTTP code returned for type PipelineAgentsOK
const PipelineAgentsOKCode int = 200

/*PipelineAgentsOK OK

swagger:response pipelineAgentsOK
*/
type PipelineAgentsOK struct {

	/*
	  In: Body
	*/
	Payload *models.Pipeline `json:"body,omitempty"`
}

// NewPipelineAgentsOK creates PipelineAgentsOK with default headers values
func NewPipelineAgentsOK() *PipelineAgentsOK {

	return &PipelineAgentsOK{}
}

// WithPayload adds the payload to the pipeline agents o k response
func (o *PipelineAgentsOK) WithPayload(payload *models.Pipeline) *PipelineAgentsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the pipeline agents o k response
func (o *PipelineAgentsOK) SetPayload(payload *models.Pipeline) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PipelineAgentsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PipelineAgentsBadRequestCode is the HTTP code returned for type PipelineAgentsBadRequest
const PipelineAgentsBadRequestCode int = 400

/*PipelineAgentsBadRequest bad request

swagger:response pipelineAgentsBadRequest
*/
type PipelineAgentsBadRequest struct {
}

// NewPipelineAgentsBadRequest creates PipelineAgentsBadRequest with default headers values
func NewPipelineAgentsBadRequest() *PipelineAgentsBadRequest {

	return &PipelineAgentsBadRequest{}
}

// WriteResponse to the client
func (o *PipelineAgentsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// PipelineAgentsInternalServerErrorCode is the HTTP code returned for type PipelineAgentsInternalServerError
const PipelineAgentsInternalServerErrorCode int = 500

/*PipelineAgentsInternalServerError internal server error

swagger:response pipelineAgentsInternalServerError
*/
type PipelineAgentsInternalServerError struct {
}

// NewPipelineAgentsInternalServerError creates PipelineAgentsInternalServerError with default headers values
func NewPipelineAgentsInternalServerError() *PipelineAgentsInternalServerError {

	return &PipelineAgentsInternalServerError{}
}

// WriteResponse to the client
func (o *PipelineAgentsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
