// Code generated by go-swagger; DO NOT EDIT.

package pipeline

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PipelinesHandlerFunc turns a function with the right signature into a pipelines handler
type PipelinesHandlerFunc func(PipelinesParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PipelinesHandlerFunc) Handle(params PipelinesParams) middleware.Responder {
	return fn(params)
}

// PipelinesHandler interface for that can handle valid pipelines params
type PipelinesHandler interface {
	Handle(PipelinesParams) middleware.Responder
}

// NewPipelines creates a new http.Handler for the pipelines operation
func NewPipelines(ctx *middleware.Context, handler PipelinesHandler) *Pipelines {
	return &Pipelines{Context: ctx, Handler: handler}
}

/*Pipelines swagger:route GET /pipelines pipeline pipelines

returns a list of all pipelines

*/
type Pipelines struct {
	Context *middleware.Context
	Handler PipelinesHandler
}

func (o *Pipelines) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPipelinesParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
