// Code generated by go-swagger; DO NOT EDIT.

package pipeline

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/metalmatze/cd/api/v1/models"
)

// PipelinesOKCode is the HTTP code returned for type PipelinesOK
const PipelinesOKCode int = 200

/*PipelinesOK OK

swagger:response pipelinesOK
*/
type PipelinesOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Pipeline `json:"body,omitempty"`
}

// NewPipelinesOK creates PipelinesOK with default headers values
func NewPipelinesOK() *PipelinesOK {

	return &PipelinesOK{}
}

// WithPayload adds the payload to the pipelines o k response
func (o *PipelinesOK) WithPayload(payload []*models.Pipeline) *PipelinesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the pipelines o k response
func (o *PipelinesOK) SetPayload(payload []*models.Pipeline) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PipelinesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]*models.Pipeline, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// PipelinesBadRequestCode is the HTTP code returned for type PipelinesBadRequest
const PipelinesBadRequestCode int = 400

/*PipelinesBadRequest bad request

swagger:response pipelinesBadRequest
*/
type PipelinesBadRequest struct {
}

// NewPipelinesBadRequest creates PipelinesBadRequest with default headers values
func NewPipelinesBadRequest() *PipelinesBadRequest {

	return &PipelinesBadRequest{}
}

// WriteResponse to the client
func (o *PipelinesBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// PipelinesInternalServerErrorCode is the HTTP code returned for type PipelinesInternalServerError
const PipelinesInternalServerErrorCode int = 500

/*PipelinesInternalServerError internal server error

swagger:response pipelinesInternalServerError
*/
type PipelinesInternalServerError struct {
}

// NewPipelinesInternalServerError creates PipelinesInternalServerError with default headers values
func NewPipelinesInternalServerError() *PipelinesInternalServerError {

	return &PipelinesInternalServerError{}
}

// WriteResponse to the client
func (o *PipelinesInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
