// Code generated by go-swagger; DO NOT EDIT.

package pipeline

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PipelineHandlerFunc turns a function with the right signature into a pipeline handler
type PipelineHandlerFunc func(PipelineParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PipelineHandlerFunc) Handle(params PipelineParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PipelineHandler interface for that can handle valid pipeline params
type PipelineHandler interface {
	Handle(PipelineParams, interface{}) middleware.Responder
}

// NewPipeline creates a new http.Handler for the pipeline operation
func NewPipeline(ctx *middleware.Context, handler PipelineHandler) *Pipeline {
	return &Pipeline{Context: ctx, Handler: handler}
}

/*Pipeline swagger:route GET /pipelines/{id} pipeline pipeline

returns a pipeline by id

*/
type Pipeline struct {
	Context *middleware.Context
	Handler PipelineHandler
}

func (o *Pipeline) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPipelineParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
