// Code generated by go-swagger; DO NOT EDIT.

package pipeline

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PipelineAgentsHandlerFunc turns a function with the right signature into a pipeline agents handler
type PipelineAgentsHandlerFunc func(PipelineAgentsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PipelineAgentsHandlerFunc) Handle(params PipelineAgentsParams) middleware.Responder {
	return fn(params)
}

// PipelineAgentsHandler interface for that can handle valid pipeline agents params
type PipelineAgentsHandler interface {
	Handle(PipelineAgentsParams) middleware.Responder
}

// NewPipelineAgents creates a new http.Handler for the pipeline agents operation
func NewPipelineAgents(ctx *middleware.Context, handler PipelineAgentsHandler) *PipelineAgents {
	return &PipelineAgents{Context: ctx, Handler: handler}
}

/*PipelineAgents swagger:route GET /pipelines/status pipeline pipelineAgents

returns the status of a running agent

*/
type PipelineAgents struct {
	Context *middleware.Context
	Handler PipelineAgentsHandler
}

func (o *PipelineAgents) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPipelineAgentsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
