// Code generated by go-swagger; DO NOT EDIT.

package pipeline

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/signalcd/signalcd/api/v1/models"
)

// PipelineCurrentOKCode is the HTTP code returned for type PipelineCurrentOK
const PipelineCurrentOKCode int = 200

/*PipelineCurrentOK OK

swagger:response pipelineCurrentOK
*/
type PipelineCurrentOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Pipeline `json:"body,omitempty"`
}

// NewPipelineCurrentOK creates PipelineCurrentOK with default headers values
func NewPipelineCurrentOK() *PipelineCurrentOK {

	return &PipelineCurrentOK{}
}

// WithPayload adds the payload to the pipeline current o k response
func (o *PipelineCurrentOK) WithPayload(payload []*models.Pipeline) *PipelineCurrentOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the pipeline current o k response
func (o *PipelineCurrentOK) SetPayload(payload []*models.Pipeline) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PipelineCurrentOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Pipeline, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// PipelineCurrentBadRequestCode is the HTTP code returned for type PipelineCurrentBadRequest
const PipelineCurrentBadRequestCode int = 400

/*PipelineCurrentBadRequest bad request

swagger:response pipelineCurrentBadRequest
*/
type PipelineCurrentBadRequest struct {
}

// NewPipelineCurrentBadRequest creates PipelineCurrentBadRequest with default headers values
func NewPipelineCurrentBadRequest() *PipelineCurrentBadRequest {

	return &PipelineCurrentBadRequest{}
}

// WriteResponse to the client
func (o *PipelineCurrentBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// PipelineCurrentInternalServerErrorCode is the HTTP code returned for type PipelineCurrentInternalServerError
const PipelineCurrentInternalServerErrorCode int = 500

/*PipelineCurrentInternalServerError internal server error

swagger:response pipelineCurrentInternalServerError
*/
type PipelineCurrentInternalServerError struct {
}

// NewPipelineCurrentInternalServerError creates PipelineCurrentInternalServerError with default headers values
func NewPipelineCurrentInternalServerError() *PipelineCurrentInternalServerError {

	return &PipelineCurrentInternalServerError{}
}

// WriteResponse to the client
func (o *PipelineCurrentInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
