// Code generated by go-swagger; DO NOT EDIT.

package pipeline

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PipelineCurrentHandlerFunc turns a function with the right signature into a pipeline current handler
type PipelineCurrentHandlerFunc func(PipelineCurrentParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PipelineCurrentHandlerFunc) Handle(params PipelineCurrentParams) middleware.Responder {
	return fn(params)
}

// PipelineCurrentHandler interface for that can handle valid pipeline current params
type PipelineCurrentHandler interface {
	Handle(PipelineCurrentParams) middleware.Responder
}

// NewPipelineCurrent creates a new http.Handler for the pipeline current operation
func NewPipelineCurrent(ctx *middleware.Context, handler PipelineCurrentHandler) *PipelineCurrent {
	return &PipelineCurrent{Context: ctx, Handler: handler}
}

/*PipelineCurrent swagger:route GET /pipeline pipeline pipelineCurrent

Returns the current executed pipeline

*/
type PipelineCurrent struct {
	Context *middleware.Context
	Handler PipelineCurrentHandler
}

func (o *PipelineCurrent) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPipelineCurrentParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
