// Code generated by go-swagger; DO NOT EDIT.

package pipeline

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// UpdateCurrentPipelineAcceptedCode is the HTTP code returned for type UpdateCurrentPipelineAccepted
const UpdateCurrentPipelineAcceptedCode int = 202

/*UpdateCurrentPipelineAccepted The current pipeline was updated successfully

swagger:response updateCurrentPipelineAccepted
*/
type UpdateCurrentPipelineAccepted struct {
}

// NewUpdateCurrentPipelineAccepted creates UpdateCurrentPipelineAccepted with default headers values
func NewUpdateCurrentPipelineAccepted() *UpdateCurrentPipelineAccepted {

	return &UpdateCurrentPipelineAccepted{}
}

// WriteResponse to the client
func (o *UpdateCurrentPipelineAccepted) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(202)
}

// UpdateCurrentPipelineBadRequestCode is the HTTP code returned for type UpdateCurrentPipelineBadRequest
const UpdateCurrentPipelineBadRequestCode int = 400

/*UpdateCurrentPipelineBadRequest bad request

swagger:response updateCurrentPipelineBadRequest
*/
type UpdateCurrentPipelineBadRequest struct {
}

// NewUpdateCurrentPipelineBadRequest creates UpdateCurrentPipelineBadRequest with default headers values
func NewUpdateCurrentPipelineBadRequest() *UpdateCurrentPipelineBadRequest {

	return &UpdateCurrentPipelineBadRequest{}
}

// WriteResponse to the client
func (o *UpdateCurrentPipelineBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

/*UpdateCurrentPipelineDefault internal server error

swagger:response updateCurrentPipelineDefault
*/
type UpdateCurrentPipelineDefault struct {
	_statusCode int
}

// NewUpdateCurrentPipelineDefault creates UpdateCurrentPipelineDefault with default headers values
func NewUpdateCurrentPipelineDefault(code int) *UpdateCurrentPipelineDefault {
	if code <= 0 {
		code = 500
	}

	return &UpdateCurrentPipelineDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the update current pipeline default response
func (o *UpdateCurrentPipelineDefault) WithStatusCode(code int) *UpdateCurrentPipelineDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the update current pipeline default response
func (o *UpdateCurrentPipelineDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WriteResponse to the client
func (o *UpdateCurrentPipelineDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(o._statusCode)
}
