// Code generated by go-swagger; DO NOT EDIT.

package pipeline

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// UpdateCurrentPipelineHandlerFunc turns a function with the right signature into a update current pipeline handler
type UpdateCurrentPipelineHandlerFunc func(UpdateCurrentPipelineParams) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateCurrentPipelineHandlerFunc) Handle(params UpdateCurrentPipelineParams) middleware.Responder {
	return fn(params)
}

// UpdateCurrentPipelineHandler interface for that can handle valid update current pipeline params
type UpdateCurrentPipelineHandler interface {
	Handle(UpdateCurrentPipelineParams) middleware.Responder
}

// NewUpdateCurrentPipeline creates a new http.Handler for the update current pipeline operation
func NewUpdateCurrentPipeline(ctx *middleware.Context, handler UpdateCurrentPipelineHandler) *UpdateCurrentPipeline {
	return &UpdateCurrentPipeline{Context: ctx, Handler: handler}
}

/*UpdateCurrentPipeline swagger:route PATCH /pipeline pipeline updateCurrentPipeline

updates the current pipeline

*/
type UpdateCurrentPipeline struct {
	Context *middleware.Context
	Handler UpdateCurrentPipelineHandler
}

func (o *UpdateCurrentPipeline) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewUpdateCurrentPipelineParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
