// Code generated by go-swagger; DO NOT EDIT.

package pipeline

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/metalmatze/cd/api/v1/models"
)

// UpdateCurrentPipelineOKCode is the HTTP code returned for type UpdateCurrentPipelineOK
const UpdateCurrentPipelineOKCode int = 200

/*UpdateCurrentPipelineOK OK

swagger:response updateCurrentPipelineOK
*/
type UpdateCurrentPipelineOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Pipeline `json:"body,omitempty"`
}

// NewUpdateCurrentPipelineOK creates UpdateCurrentPipelineOK with default headers values
func NewUpdateCurrentPipelineOK() *UpdateCurrentPipelineOK {

	return &UpdateCurrentPipelineOK{}
}

// WithPayload adds the payload to the update current pipeline o k response
func (o *UpdateCurrentPipelineOK) WithPayload(payload []*models.Pipeline) *UpdateCurrentPipelineOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update current pipeline o k response
func (o *UpdateCurrentPipelineOK) SetPayload(payload []*models.Pipeline) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateCurrentPipelineOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]*models.Pipeline, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// UpdateCurrentPipelineBadRequestCode is the HTTP code returned for type UpdateCurrentPipelineBadRequest
const UpdateCurrentPipelineBadRequestCode int = 400

/*UpdateCurrentPipelineBadRequest bad request

swagger:response updateCurrentPipelineBadRequest
*/
type UpdateCurrentPipelineBadRequest struct {
}

// NewUpdateCurrentPipelineBadRequest creates UpdateCurrentPipelineBadRequest with default headers values
func NewUpdateCurrentPipelineBadRequest() *UpdateCurrentPipelineBadRequest {

	return &UpdateCurrentPipelineBadRequest{}
}

// WriteResponse to the client
func (o *UpdateCurrentPipelineBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

/*UpdateCurrentPipelineDefault internal server error

swagger:response updateCurrentPipelineDefault
*/
type UpdateCurrentPipelineDefault struct {
	_statusCode int
}

// NewUpdateCurrentPipelineDefault creates UpdateCurrentPipelineDefault with default headers values
func NewUpdateCurrentPipelineDefault(code int) *UpdateCurrentPipelineDefault {
	if code <= 0 {
		code = 500
	}

	return &UpdateCurrentPipelineDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the update current pipeline default response
func (o *UpdateCurrentPipelineDefault) WithStatusCode(code int) *UpdateCurrentPipelineDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the update current pipeline default response
func (o *UpdateCurrentPipelineDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WriteResponse to the client
func (o *UpdateCurrentPipelineDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(o._statusCode)
}
