/*
 * SignalCD
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PipelineSteps struct {
	Name string `json:"name,omitempty"`

	Image string `json:"image,omitempty"`

	ImagePullSecrets []string `json:"imagePullSecrets,omitempty"`

	Commands []string `json:"commands,omitempty"`
}
