// Code generated by go-swagger; DO NOT EDIT.

package pipeline

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPipelineParams creates a new PipelineParams object
// with the default values initialized.
func NewPipelineParams() *PipelineParams {
	var ()
	return &PipelineParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPipelineParamsWithTimeout creates a new PipelineParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPipelineParamsWithTimeout(timeout time.Duration) *PipelineParams {
	var ()
	return &PipelineParams{

		timeout: timeout,
	}
}

// NewPipelineParamsWithContext creates a new PipelineParams object
// with the default values initialized, and the ability to set a context for a request
func NewPipelineParamsWithContext(ctx context.Context) *PipelineParams {
	var ()
	return &PipelineParams{

		Context: ctx,
	}
}

// NewPipelineParamsWithHTTPClient creates a new PipelineParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPipelineParamsWithHTTPClient(client *http.Client) *PipelineParams {
	var ()
	return &PipelineParams{
		HTTPClient: client,
	}
}

/*PipelineParams contains all the parameters to send to the API endpoint
for the pipeline operation typically these are written to a http.Request
*/
type PipelineParams struct {

	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the pipeline params
func (o *PipelineParams) WithTimeout(timeout time.Duration) *PipelineParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the pipeline params
func (o *PipelineParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the pipeline params
func (o *PipelineParams) WithContext(ctx context.Context) *PipelineParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the pipeline params
func (o *PipelineParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the pipeline params
func (o *PipelineParams) WithHTTPClient(client *http.Client) *PipelineParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the pipeline params
func (o *PipelineParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the pipeline params
func (o *PipelineParams) WithID(id string) *PipelineParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the pipeline params
func (o *PipelineParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PipelineParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
