// Code generated by go-swagger; DO NOT EDIT.

package pipeline

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/signalcd/signalcd/api/v1/models"
)

// PipelinesReader is a Reader for the Pipelines structure.
type PipelinesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PipelinesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPipelinesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewPipelinesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewPipelinesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPipelinesOK creates a PipelinesOK with default headers values
func NewPipelinesOK() *PipelinesOK {
	return &PipelinesOK{}
}

/*PipelinesOK handles this case with default header values.

OK
*/
type PipelinesOK struct {
	Payload []*models.Pipeline
}

func (o *PipelinesOK) Error() string {
	return fmt.Sprintf("[GET /pipelines][%d] pipelinesOK  %+v", 200, o.Payload)
}

func (o *PipelinesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPipelinesBadRequest creates a PipelinesBadRequest with default headers values
func NewPipelinesBadRequest() *PipelinesBadRequest {
	return &PipelinesBadRequest{}
}

/*PipelinesBadRequest handles this case with default header values.

bad request
*/
type PipelinesBadRequest struct {
}

func (o *PipelinesBadRequest) Error() string {
	return fmt.Sprintf("[GET /pipelines][%d] pipelinesBadRequest ", 400)
}

func (o *PipelinesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPipelinesInternalServerError creates a PipelinesInternalServerError with default headers values
func NewPipelinesInternalServerError() *PipelinesInternalServerError {
	return &PipelinesInternalServerError{}
}

/*PipelinesInternalServerError handles this case with default header values.

internal server error
*/
type PipelinesInternalServerError struct {
}

func (o *PipelinesInternalServerError) Error() string {
	return fmt.Sprintf("[GET /pipelines][%d] pipelinesInternalServerError ", 500)
}

func (o *PipelinesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
