/*
 * SignalCD
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"time"
)

// DeploymentStepStatus struct for DeploymentStepStatus
type DeploymentStepStatus struct {
	Phase   string    `json:"phase"`
	Started time.Time `json:"started"`
	Stopped time.Time `json:"stopped,omitempty"`
}
