/*
 * SignalCD
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

// PipelineSteps struct for PipelineSteps
type PipelineSteps struct {
	Name     string   `json:"name,omitempty"`
	Image    string   `json:"image,omitempty"`
	Commands []string `json:"commands,omitempty"`
}
