/*
 * SignalCD
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

// DeploymentStatusUpdate struct for DeploymentStatusUpdate
type DeploymentStatusUpdate struct {
	Agent string `json:"agent"`
	Step  int64  `json:"step"`
	Phase string `json:"phase,omitempty"`
}
