/*
 * SignalCD
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi
import (
	"time"
)
// Deployment struct for Deployment
type Deployment struct {
	Number int64 `json:"number,omitempty"`
	Created time.Time `json:"created,omitempty"`
	Started time.Time `json:"started,omitempty"`
	Finished time.Time `json:"finished,omitempty"`
}
