/*
 * SignalCD
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"time"
)

// Pipeline struct for Pipeline
type Pipeline struct {
	Id      string    `json:"id"`
	Name    string    `json:"name,omitempty"`
	Created time.Time `json:"created,omitempty"`
}
