/*
 * SignalCD
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi
// InlineObject struct for InlineObject
type InlineObject struct {
	PipelineID string `json:"pipelineID,omitempty"`
}
