/**
 * SignalCD
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DeploymentStatusUpdate model module.
 * @module model/DeploymentStatusUpdate
 * @version 0.0.0
 */
class DeploymentStatusUpdate {
    /**
     * Constructs a new <code>DeploymentStatusUpdate</code>.
     * @alias module:model/DeploymentStatusUpdate
     * @param agent {String} 
     * @param step {Number} 
     */
    constructor(agent, step) { 
        
        DeploymentStatusUpdate.initialize(this, agent, step);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, agent, step) { 
        obj['agent'] = agent;
        obj['step'] = step;
    }

    /**
     * Constructs a <code>DeploymentStatusUpdate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DeploymentStatusUpdate} obj Optional instance to populate.
     * @return {module:model/DeploymentStatusUpdate} The populated <code>DeploymentStatusUpdate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DeploymentStatusUpdate();

            if (data.hasOwnProperty('agent')) {
                obj['agent'] = ApiClient.convertToType(data['agent'], 'String');
            }
            if (data.hasOwnProperty('step')) {
                obj['step'] = ApiClient.convertToType(data['step'], 'Number');
            }
            if (data.hasOwnProperty('phase')) {
                obj['phase'] = ApiClient.convertToType(data['phase'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} agent
 */
DeploymentStatusUpdate.prototype['agent'] = undefined;

/**
 * @member {Number} step
 */
DeploymentStatusUpdate.prototype['step'] = undefined;

/**
 * @member {module:model/DeploymentStatusUpdate.PhaseEnum} phase
 */
DeploymentStatusUpdate.prototype['phase'] = undefined;





/**
 * Allowed values for the <code>phase</code> property.
 * @enum {String}
 * @readonly
 */
DeploymentStatusUpdate['PhaseEnum'] = {

    /**
     * value: "unknown"
     * @const
     */
    "unknown": "unknown",

    /**
     * value: "success"
     * @const
     */
    "success": "success",

    /**
     * value: "failure"
     * @const
     */
    "failure": "failure",

    /**
     * value: "progress"
     * @const
     */
    "progress": "progress",

    /**
     * value: "pending"
     * @const
     */
    "pending": "pending",

    /**
     * value: "killed"
     * @const
     */
    "killed": "killed"
};



export default DeploymentStatusUpdate;

