/**
 * SignalCD
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DeploymentStepStatus model module.
 * @module model/DeploymentStepStatus
 * @version 0.0.0
 */
class DeploymentStepStatus {
    /**
     * Constructs a new <code>DeploymentStepStatus</code>.
     * @alias module:model/DeploymentStepStatus
     * @param phase {String} 
     * @param started {Date} 
     */
    constructor(phase, started) { 
        
        DeploymentStepStatus.initialize(this, phase, started);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, phase, started) { 
        obj['phase'] = phase;
        obj['started'] = started;
    }

    /**
     * Constructs a <code>DeploymentStepStatus</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DeploymentStepStatus} obj Optional instance to populate.
     * @return {module:model/DeploymentStepStatus} The populated <code>DeploymentStepStatus</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DeploymentStepStatus();

            if (data.hasOwnProperty('phase')) {
                obj['phase'] = ApiClient.convertToType(data['phase'], 'String');
            }
            if (data.hasOwnProperty('started')) {
                obj['started'] = ApiClient.convertToType(data['started'], 'Date');
            }
            if (data.hasOwnProperty('stopped')) {
                obj['stopped'] = ApiClient.convertToType(data['stopped'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * @member {String} phase
 */
DeploymentStepStatus.prototype['phase'] = undefined;

/**
 * @member {Date} started
 */
DeploymentStepStatus.prototype['started'] = undefined;

/**
 * @member {Date} stopped
 */
DeploymentStepStatus.prototype['stopped'] = undefined;






export default DeploymentStepStatus;

