/**
 * SignalCD
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SetCurrentDeployment model module.
 * @module model/SetCurrentDeployment
 * @version 0.0.0
 */
class SetCurrentDeployment {
    /**
     * Constructs a new <code>SetCurrentDeployment</code>.
     * @alias module:model/SetCurrentDeployment
     * @param pipelineID {String} 
     */
    constructor(pipelineID) { 
        
        SetCurrentDeployment.initialize(this, pipelineID);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, pipelineID) { 
        obj['pipelineID'] = pipelineID;
    }

    /**
     * Constructs a <code>SetCurrentDeployment</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SetCurrentDeployment} obj Optional instance to populate.
     * @return {module:model/SetCurrentDeployment} The populated <code>SetCurrentDeployment</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SetCurrentDeployment();

            if (data.hasOwnProperty('pipelineID')) {
                obj['pipelineID'] = ApiClient.convertToType(data['pipelineID'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} pipelineID
 */
SetCurrentDeployment.prototype['pipelineID'] = undefined;






export default SetCurrentDeployment;

