// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi CD Swagger Spec
Swagger 2.0 specification for CD

Terms Of Service:

http://swagger.io/terms/


    Schemes:
      http
      https
    Host: localhost:6660
    BasePath: /v1
    Version: v0.01

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
