// Code generated by go-swagger; DO NOT EDIT.

package deployments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/signalcd/signalcd/api/v1/models"
)

// CurrentDeploymentOKCode is the HTTP code returned for type CurrentDeploymentOK
const CurrentDeploymentOKCode int = 200

/*CurrentDeploymentOK OK

swagger:response currentDeploymentOK
*/
type CurrentDeploymentOK struct {

	/*
	  In: Body
	*/
	Payload *models.Deployment `json:"body,omitempty"`
}

// NewCurrentDeploymentOK creates CurrentDeploymentOK with default headers values
func NewCurrentDeploymentOK() *CurrentDeploymentOK {

	return &CurrentDeploymentOK{}
}

// WithPayload adds the payload to the current deployment o k response
func (o *CurrentDeploymentOK) WithPayload(payload *models.Deployment) *CurrentDeploymentOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the current deployment o k response
func (o *CurrentDeploymentOK) SetPayload(payload *models.Deployment) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CurrentDeploymentOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
