// Code generated by go-swagger; DO NOT EDIT.

package deployments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// SetCurrentDeploymentHandlerFunc turns a function with the right signature into a set current deployment handler
type SetCurrentDeploymentHandlerFunc func(SetCurrentDeploymentParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn SetCurrentDeploymentHandlerFunc) Handle(params SetCurrentDeploymentParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// SetCurrentDeploymentHandler interface for that can handle valid set current deployment params
type SetCurrentDeploymentHandler interface {
	Handle(SetCurrentDeploymentParams, interface{}) middleware.Responder
}

// NewSetCurrentDeployment creates a new http.Handler for the set current deployment operation
func NewSetCurrentDeployment(ctx *middleware.Context, handler SetCurrentDeploymentHandler) *SetCurrentDeployment {
	return &SetCurrentDeployment{Context: ctx, Handler: handler}
}

/*SetCurrentDeployment swagger:route POST /deployments/current deployments setCurrentDeployment

Schedule a new deployment

*/
type SetCurrentDeployment struct {
	Context *middleware.Context
	Handler SetCurrentDeploymentHandler
}

func (o *SetCurrentDeployment) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewSetCurrentDeploymentParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
