// Code generated by protoc-gen-go. DO NOT EDIT.
// source: signalcd/proto/check.proto

package signalcdproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CheckStatus_Phase int32

const (
	CheckStatus_UNKNOWN  CheckStatus_Phase = 0
	CheckStatus_SUCCESS  CheckStatus_Phase = 1
	CheckStatus_FAILURE  CheckStatus_Phase = 2
	CheckStatus_CHECKING CheckStatus_Phase = 3
	CheckStatus_KILLED   CheckStatus_Phase = 5
)

var CheckStatus_Phase_name = map[int32]string{
	0: "UNKNOWN",
	1: "SUCCESS",
	2: "FAILURE",
	3: "CHECKING",
	5: "KILLED",
}
var CheckStatus_Phase_value = map[string]int32{
	"UNKNOWN":  0,
	"SUCCESS":  1,
	"FAILURE":  2,
	"CHECKING": 3,
	"KILLED":   5,
}

func (x CheckStatus_Phase) String() string {
	return proto.EnumName(CheckStatus_Phase_name, int32(x))
}
func (CheckStatus_Phase) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_check_a85a9d31f1f95609, []int{0, 0}
}

type CheckStatus struct {
	Phase                CheckStatus_Phase `protobuf:"varint,1,opt,name=phase,proto3,enum=signalcd.CheckStatus_Phase" json:"phase,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CheckStatus) Reset()         { *m = CheckStatus{} }
func (m *CheckStatus) String() string { return proto.CompactTextString(m) }
func (*CheckStatus) ProtoMessage()    {}
func (*CheckStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_check_a85a9d31f1f95609, []int{0}
}
func (m *CheckStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckStatus.Unmarshal(m, b)
}
func (m *CheckStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckStatus.Marshal(b, m, deterministic)
}
func (dst *CheckStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckStatus.Merge(dst, src)
}
func (m *CheckStatus) XXX_Size() int {
	return xxx_messageInfo_CheckStatus.Size(m)
}
func (m *CheckStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckStatus.DiscardUnknown(m)
}

var xxx_messageInfo_CheckStatus proto.InternalMessageInfo

func (m *CheckStatus) GetPhase() CheckStatus_Phase {
	if m != nil {
		return m.Phase
	}
	return CheckStatus_UNKNOWN
}

type SetCheckStatusRequest struct {
	DeploymentNumber     int64        `protobuf:"varint,1,opt,name=deploymentNumber,proto3" json:"deploymentNumber,omitempty"`
	Number               int64        `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	Status               *CheckStatus `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SetCheckStatusRequest) Reset()         { *m = SetCheckStatusRequest{} }
func (m *SetCheckStatusRequest) String() string { return proto.CompactTextString(m) }
func (*SetCheckStatusRequest) ProtoMessage()    {}
func (*SetCheckStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_check_a85a9d31f1f95609, []int{1}
}
func (m *SetCheckStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetCheckStatusRequest.Unmarshal(m, b)
}
func (m *SetCheckStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetCheckStatusRequest.Marshal(b, m, deterministic)
}
func (dst *SetCheckStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetCheckStatusRequest.Merge(dst, src)
}
func (m *SetCheckStatusRequest) XXX_Size() int {
	return xxx_messageInfo_SetCheckStatusRequest.Size(m)
}
func (m *SetCheckStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetCheckStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetCheckStatusRequest proto.InternalMessageInfo

func (m *SetCheckStatusRequest) GetDeploymentNumber() int64 {
	if m != nil {
		return m.DeploymentNumber
	}
	return 0
}

func (m *SetCheckStatusRequest) GetNumber() int64 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *SetCheckStatusRequest) GetStatus() *CheckStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type SetCheckStatusResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetCheckStatusResponse) Reset()         { *m = SetCheckStatusResponse{} }
func (m *SetCheckStatusResponse) String() string { return proto.CompactTextString(m) }
func (*SetCheckStatusResponse) ProtoMessage()    {}
func (*SetCheckStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_check_a85a9d31f1f95609, []int{2}
}
func (m *SetCheckStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetCheckStatusResponse.Unmarshal(m, b)
}
func (m *SetCheckStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetCheckStatusResponse.Marshal(b, m, deterministic)
}
func (dst *SetCheckStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetCheckStatusResponse.Merge(dst, src)
}
func (m *SetCheckStatusResponse) XXX_Size() int {
	return xxx_messageInfo_SetCheckStatusResponse.Size(m)
}
func (m *SetCheckStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetCheckStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetCheckStatusResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*CheckStatus)(nil), "signalcd.CheckStatus")
	proto.RegisterType((*SetCheckStatusRequest)(nil), "signalcd.SetCheckStatusRequest")
	proto.RegisterType((*SetCheckStatusResponse)(nil), "signalcd.SetCheckStatusResponse")
	proto.RegisterEnum("signalcd.CheckStatus_Phase", CheckStatus_Phase_name, CheckStatus_Phase_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CheckServiceClient is the client API for CheckService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CheckServiceClient interface {
	SetCheckStatus(ctx context.Context, in *SetCheckStatusRequest, opts ...grpc.CallOption) (*SetCheckStatusResponse, error)
}

type checkServiceClient struct {
	cc *grpc.ClientConn
}

func NewCheckServiceClient(cc *grpc.ClientConn) CheckServiceClient {
	return &checkServiceClient{cc}
}

func (c *checkServiceClient) SetCheckStatus(ctx context.Context, in *SetCheckStatusRequest, opts ...grpc.CallOption) (*SetCheckStatusResponse, error) {
	out := new(SetCheckStatusResponse)
	err := c.cc.Invoke(ctx, "/signalcd.CheckService/SetCheckStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CheckServiceServer is the server API for CheckService service.
type CheckServiceServer interface {
	SetCheckStatus(context.Context, *SetCheckStatusRequest) (*SetCheckStatusResponse, error)
}

func RegisterCheckServiceServer(s *grpc.Server, srv CheckServiceServer) {
	s.RegisterService(&_CheckService_serviceDesc, srv)
}

func _CheckService_SetCheckStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetCheckStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckServiceServer).SetCheckStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/signalcd.CheckService/SetCheckStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckServiceServer).SetCheckStatus(ctx, req.(*SetCheckStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CheckService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "signalcd.CheckService",
	HandlerType: (*CheckServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetCheckStatus",
			Handler:    _CheckService_SetCheckStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "signalcd/proto/check.proto",
}

func init() { proto.RegisterFile("signalcd/proto/check.proto", fileDescriptor_check_a85a9d31f1f95609) }

var fileDescriptor_check_a85a9d31f1f95609 = []byte{
	// 292 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xd1, 0x4a, 0xf3, 0x40,
	0x10, 0x85, 0xff, 0xb4, 0x34, 0x7f, 0x99, 0xd4, 0xba, 0x2c, 0xb4, 0x84, 0x7a, 0x61, 0xc8, 0x55,
	0x11, 0x4c, 0x31, 0x3e, 0x81, 0xc6, 0x68, 0x43, 0x42, 0x94, 0x2c, 0x41, 0xf0, 0x2e, 0x4d, 0x07,
	0x5b, 0x6c, 0x93, 0x98, 0xdd, 0x08, 0xbe, 0x82, 0x4f, 0x2d, 0xd9, 0x34, 0x58, 0xb5, 0x5e, 0xed,
	0x9e, 0x99, 0x8f, 0x99, 0x73, 0x18, 0x98, 0xf0, 0xf5, 0x73, 0x96, 0x6c, 0xd2, 0xe5, 0xac, 0x28,
	0x73, 0x91, 0xcf, 0xd2, 0x15, 0xa6, 0x2f, 0x96, 0xfc, 0xd3, 0x7e, 0xdb, 0x33, 0x3f, 0x14, 0xd0,
	0x9c, 0xba, 0xc3, 0x44, 0x22, 0x2a, 0x4e, 0x2f, 0xa0, 0x57, 0xac, 0x12, 0x8e, 0xba, 0x62, 0x28,
	0xd3, 0xa1, 0x7d, 0x62, 0xb5, 0xa4, 0xb5, 0x47, 0x59, 0x0f, 0x35, 0x12, 0x35, 0xa4, 0x39, 0x87,
	0x9e, 0xd4, 0x54, 0x83, 0xff, 0x71, 0xe8, 0x87, 0xf7, 0x8f, 0x21, 0xf9, 0x57, 0x0b, 0x16, 0x3b,
	0x8e, 0xcb, 0x18, 0x51, 0x6a, 0x71, 0x7b, 0xe5, 0x05, 0x71, 0xe4, 0x92, 0x0e, 0x1d, 0x40, 0xdf,
	0x99, 0xbb, 0x8e, 0xef, 0x85, 0x77, 0xa4, 0x4b, 0x01, 0x54, 0xdf, 0x0b, 0x02, 0xf7, 0x86, 0xf4,
	0x6a, 0x33, 0x23, 0x86, 0x62, 0x6f, 0x53, 0x84, 0xaf, 0x15, 0x72, 0x41, 0xcf, 0x80, 0x2c, 0xb1,
	0xd8, 0xe4, 0xef, 0x5b, 0xcc, 0x44, 0x58, 0x6d, 0x17, 0x58, 0x4a, 0x87, 0xdd, 0xe8, 0x57, 0x9d,
	0x8e, 0x41, 0xcd, 0x1a, 0xa2, 0x23, 0x89, 0x9d, 0xa2, 0xe7, 0xa0, 0x72, 0x39, 0x54, 0xef, 0x1a,
	0xca, 0x54, 0xb3, 0x47, 0x07, 0xb3, 0x45, 0x3b, 0xc8, 0xd4, 0x61, 0xfc, 0xd3, 0x0b, 0x2f, 0xf2,
	0x8c, 0xa3, 0x9d, 0xc2, 0xa0, 0x29, 0x63, 0xf9, 0xb6, 0x4e, 0x91, 0x32, 0x18, 0x7e, 0x27, 0xe9,
	0xe9, 0xd7, 0xe8, 0x83, 0x79, 0x26, 0xc6, 0xdf, 0x40, 0xb3, 0xe4, 0xfa, 0xf8, 0xe9, 0xa8, 0x45,
	0xe4, 0xcd, 0x16, 0xaa, 0x7c, 0x2e, 0x3f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x93, 0x34, 0xd4, 0x25,
	0xd8, 0x01, 0x00, 0x00,
}
