// Code generated by protoc-gen-go. DO NOT EDIT.
// source: signalcd/proto/types.proto

package signalcdproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DeploymentStatus_Phase int32

const (
	DeploymentStatus_UNKNOWN  DeploymentStatus_Phase = 0
	DeploymentStatus_SUCCESS  DeploymentStatus_Phase = 1
	DeploymentStatus_FAILURE  DeploymentStatus_Phase = 2
	DeploymentStatus_PROGRESS DeploymentStatus_Phase = 3
	DeploymentStatus_PENDING  DeploymentStatus_Phase = 4
	DeploymentStatus_KILLED   DeploymentStatus_Phase = 5
)

var DeploymentStatus_Phase_name = map[int32]string{
	0: "UNKNOWN",
	1: "SUCCESS",
	2: "FAILURE",
	3: "PROGRESS",
	4: "PENDING",
	5: "KILLED",
}

var DeploymentStatus_Phase_value = map[string]int32{
	"UNKNOWN":  0,
	"SUCCESS":  1,
	"FAILURE":  2,
	"PROGRESS": 3,
	"PENDING":  4,
	"KILLED":   5,
}

func (x DeploymentStatus_Phase) String() string {
	return proto.EnumName(DeploymentStatus_Phase_name, int32(x))
}

func (DeploymentStatus_Phase) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7c4df36a331e75e3, []int{1, 0}
}

type Deployment struct {
	Number               int64             `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	Created              int64             `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"`
	Started              int64             `protobuf:"varint,3,opt,name=started,proto3" json:"started,omitempty"`
	Finished             int64             `protobuf:"varint,4,opt,name=finished,proto3" json:"finished,omitempty"`
	Status               *DeploymentStatus `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Pipeline             *Pipeline         `protobuf:"bytes,6,opt,name=pipeline,proto3" json:"pipeline,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Deployment) Reset()         { *m = Deployment{} }
func (m *Deployment) String() string { return proto.CompactTextString(m) }
func (*Deployment) ProtoMessage()    {}
func (*Deployment) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c4df36a331e75e3, []int{0}
}

func (m *Deployment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Deployment.Unmarshal(m, b)
}
func (m *Deployment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Deployment.Marshal(b, m, deterministic)
}
func (m *Deployment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Deployment.Merge(m, src)
}
func (m *Deployment) XXX_Size() int {
	return xxx_messageInfo_Deployment.Size(m)
}
func (m *Deployment) XXX_DiscardUnknown() {
	xxx_messageInfo_Deployment.DiscardUnknown(m)
}

var xxx_messageInfo_Deployment proto.InternalMessageInfo

func (m *Deployment) GetNumber() int64 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *Deployment) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *Deployment) GetStarted() int64 {
	if m != nil {
		return m.Started
	}
	return 0
}

func (m *Deployment) GetFinished() int64 {
	if m != nil {
		return m.Finished
	}
	return 0
}

func (m *Deployment) GetStatus() *DeploymentStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *Deployment) GetPipeline() *Pipeline {
	if m != nil {
		return m.Pipeline
	}
	return nil
}

type DeploymentStatus struct {
	Phase                DeploymentStatus_Phase `protobuf:"varint,1,opt,name=phase,proto3,enum=signalcd.DeploymentStatus_Phase" json:"phase,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *DeploymentStatus) Reset()         { *m = DeploymentStatus{} }
func (m *DeploymentStatus) String() string { return proto.CompactTextString(m) }
func (*DeploymentStatus) ProtoMessage()    {}
func (*DeploymentStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c4df36a331e75e3, []int{1}
}

func (m *DeploymentStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeploymentStatus.Unmarshal(m, b)
}
func (m *DeploymentStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeploymentStatus.Marshal(b, m, deterministic)
}
func (m *DeploymentStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeploymentStatus.Merge(m, src)
}
func (m *DeploymentStatus) XXX_Size() int {
	return xxx_messageInfo_DeploymentStatus.Size(m)
}
func (m *DeploymentStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_DeploymentStatus.DiscardUnknown(m)
}

var xxx_messageInfo_DeploymentStatus proto.InternalMessageInfo

func (m *DeploymentStatus) GetPhase() DeploymentStatus_Phase {
	if m != nil {
		return m.Phase
	}
	return DeploymentStatus_UNKNOWN
}

type Pipeline struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Steps                []*Step  `protobuf:"bytes,3,rep,name=steps,proto3" json:"steps,omitempty"`
	Checks               []*Check `protobuf:"bytes,4,rep,name=checks,proto3" json:"checks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pipeline) Reset()         { *m = Pipeline{} }
func (m *Pipeline) String() string { return proto.CompactTextString(m) }
func (*Pipeline) ProtoMessage()    {}
func (*Pipeline) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c4df36a331e75e3, []int{2}
}

func (m *Pipeline) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pipeline.Unmarshal(m, b)
}
func (m *Pipeline) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pipeline.Marshal(b, m, deterministic)
}
func (m *Pipeline) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pipeline.Merge(m, src)
}
func (m *Pipeline) XXX_Size() int {
	return xxx_messageInfo_Pipeline.Size(m)
}
func (m *Pipeline) XXX_DiscardUnknown() {
	xxx_messageInfo_Pipeline.DiscardUnknown(m)
}

var xxx_messageInfo_Pipeline proto.InternalMessageInfo

func (m *Pipeline) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Pipeline) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Pipeline) GetSteps() []*Step {
	if m != nil {
		return m.Steps
	}
	return nil
}

func (m *Pipeline) GetChecks() []*Check {
	if m != nil {
		return m.Checks
	}
	return nil
}

type Step struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Image                string   `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	ImagePullSecrets     []string `protobuf:"bytes,3,rep,name=ImagePullSecrets,proto3" json:"ImagePullSecrets,omitempty"`
	Commands             []string `protobuf:"bytes,4,rep,name=commands,proto3" json:"commands,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Step) Reset()         { *m = Step{} }
func (m *Step) String() string { return proto.CompactTextString(m) }
func (*Step) ProtoMessage()    {}
func (*Step) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c4df36a331e75e3, []int{3}
}

func (m *Step) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Step.Unmarshal(m, b)
}
func (m *Step) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Step.Marshal(b, m, deterministic)
}
func (m *Step) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Step.Merge(m, src)
}
func (m *Step) XXX_Size() int {
	return xxx_messageInfo_Step.Size(m)
}
func (m *Step) XXX_DiscardUnknown() {
	xxx_messageInfo_Step.DiscardUnknown(m)
}

var xxx_messageInfo_Step proto.InternalMessageInfo

func (m *Step) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Step) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *Step) GetImagePullSecrets() []string {
	if m != nil {
		return m.ImagePullSecrets
	}
	return nil
}

func (m *Step) GetCommands() []string {
	if m != nil {
		return m.Commands
	}
	return nil
}

type Check struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Image                string   `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	ImagePullSecrets     []string `protobuf:"bytes,3,rep,name=ImagePullSecrets,proto3" json:"ImagePullSecrets,omitempty"`
	Duration             int64    `protobuf:"varint,4,opt,name=duration,proto3" json:"duration,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Check) Reset()         { *m = Check{} }
func (m *Check) String() string { return proto.CompactTextString(m) }
func (*Check) ProtoMessage()    {}
func (*Check) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c4df36a331e75e3, []int{4}
}

func (m *Check) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Check.Unmarshal(m, b)
}
func (m *Check) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Check.Marshal(b, m, deterministic)
}
func (m *Check) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Check.Merge(m, src)
}
func (m *Check) XXX_Size() int {
	return xxx_messageInfo_Check.Size(m)
}
func (m *Check) XXX_DiscardUnknown() {
	xxx_messageInfo_Check.DiscardUnknown(m)
}

var xxx_messageInfo_Check proto.InternalMessageInfo

func (m *Check) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Check) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *Check) GetImagePullSecrets() []string {
	if m != nil {
		return m.ImagePullSecrets
	}
	return nil
}

func (m *Check) GetDuration() int64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func init() {
	proto.RegisterEnum("signalcd.DeploymentStatus_Phase", DeploymentStatus_Phase_name, DeploymentStatus_Phase_value)
	proto.RegisterType((*Deployment)(nil), "signalcd.Deployment")
	proto.RegisterType((*DeploymentStatus)(nil), "signalcd.DeploymentStatus")
	proto.RegisterType((*Pipeline)(nil), "signalcd.Pipeline")
	proto.RegisterType((*Step)(nil), "signalcd.Step")
	proto.RegisterType((*Check)(nil), "signalcd.Check")
}

func init() { proto.RegisterFile("signalcd/proto/types.proto", fileDescriptor_7c4df36a331e75e3) }

var fileDescriptor_7c4df36a331e75e3 = []byte{
	// 436 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x93, 0x4f, 0x8b, 0xd3, 0x40,
	0x18, 0xc6, 0x4d, 0xf3, 0x67, 0xd3, 0xb7, 0xda, 0x0d, 0x2f, 0x22, 0xa1, 0xa7, 0x12, 0x04, 0x8b,
	0x87, 0x2c, 0x54, 0xf0, 0xae, 0x6d, 0x5d, 0xca, 0x96, 0x6c, 0x98, 0x50, 0x04, 0x6f, 0xb3, 0xc9,
	0xb8, 0x1d, 0xcc, 0x3f, 0x32, 0x53, 0xb0, 0x07, 0x3f, 0x8c, 0xdf, 0xca, 0x8f, 0x23, 0x33, 0xc9,
	0xb4, 0xa2, 0x78, 0xdc, 0x53, 0xe6, 0x99, 0xdf, 0xf3, 0xe6, 0x79, 0x32, 0x4c, 0x60, 0x26, 0xf8,
	0x63, 0x4d, 0xcb, 0xbc, 0xb8, 0x69, 0xbb, 0x46, 0x36, 0x37, 0xf2, 0xd4, 0x32, 0x11, 0xeb, 0x35,
	0xfa, 0x86, 0x45, 0xbf, 0x2c, 0x80, 0x35, 0x6b, 0xcb, 0xe6, 0x54, 0xb1, 0x5a, 0xe2, 0x2b, 0xf0,
	0xea, 0x63, 0xf5, 0xc0, 0xba, 0xd0, 0x9a, 0x5b, 0x0b, 0x9b, 0x0c, 0x0a, 0x43, 0xb8, 0xca, 0x3b,
	0x46, 0x25, 0x2b, 0xc2, 0x91, 0x06, 0x46, 0x2a, 0x22, 0x24, 0xed, 0x14, 0xb1, 0x7b, 0x32, 0x48,
	0x9c, 0x81, 0xff, 0x95, 0xd7, 0x5c, 0x1c, 0x58, 0x11, 0x3a, 0x1a, 0x9d, 0x35, 0x2e, 0xc1, 0x13,
	0x92, 0xca, 0xa3, 0x08, 0xdd, 0xb9, 0xb5, 0x98, 0x2c, 0x67, 0xb1, 0x69, 0x14, 0x5f, 0xda, 0x64,
	0xda, 0x41, 0x06, 0x27, 0xc6, 0xe0, 0xb7, 0xbc, 0x65, 0x25, 0xaf, 0x59, 0xe8, 0xe9, 0x29, 0xbc,
	0x4c, 0xa5, 0x03, 0x21, 0x67, 0x4f, 0xf4, 0xd3, 0x82, 0xe0, 0xef, 0x97, 0xe1, 0x7b, 0x70, 0xdb,
	0x03, 0x15, 0x4c, 0x7f, 0xdf, 0x74, 0x39, 0xff, 0x7f, 0x6e, 0x9c, 0x2a, 0x1f, 0xe9, 0xed, 0xd1,
	0x1e, 0x5c, 0xad, 0x71, 0x02, 0x57, 0xfb, 0xe4, 0x2e, 0xb9, 0xff, 0x9c, 0x04, 0xcf, 0x94, 0xc8,
	0xf6, 0xab, 0xd5, 0x26, 0xcb, 0x02, 0x4b, 0x89, 0x4f, 0x1f, 0xb6, 0xbb, 0x3d, 0xd9, 0x04, 0x23,
	0x7c, 0x0e, 0x7e, 0x4a, 0xee, 0x6f, 0x89, 0x42, 0xb6, 0x42, 0xe9, 0x26, 0x59, 0x6f, 0x93, 0xdb,
	0xc0, 0x41, 0x00, 0xef, 0x6e, 0xbb, 0xdb, 0x6d, 0xd6, 0x81, 0x1b, 0xfd, 0x00, 0xdf, 0x34, 0xc7,
	0x29, 0x8c, 0x78, 0xa1, 0x7b, 0x8d, 0xc9, 0x88, 0x17, 0x88, 0xe0, 0xd4, 0xb4, 0x62, 0xfa, 0xc0,
	0xc7, 0x44, 0xaf, 0xf1, 0x35, 0xb8, 0x42, 0xb2, 0x56, 0x84, 0xf6, 0xdc, 0x5e, 0x4c, 0x96, 0xd3,
	0x4b, 0xfd, 0x4c, 0xb2, 0x96, 0xf4, 0x10, 0xdf, 0x80, 0x97, 0x1f, 0x58, 0xfe, 0x4d, 0x84, 0x8e,
	0xb6, 0x5d, 0x5f, 0x6c, 0x2b, 0xb5, 0x4f, 0x06, 0x1c, 0x7d, 0x07, 0x47, 0xcd, 0x9d, 0xa3, 0xac,
	0x3f, 0xa2, 0x5e, 0x82, 0xcb, 0x2b, 0xfa, 0x68, 0xf2, 0x7b, 0x81, 0x6f, 0x21, 0xd8, 0xaa, 0x45,
	0x7a, 0x2c, 0xcb, 0x8c, 0xe5, 0x1d, 0x93, 0x7d, 0x97, 0x31, 0xf9, 0x67, 0x5f, 0x5d, 0x80, 0xbc,
	0xa9, 0x2a, 0x5a, 0x17, 0x7d, 0x91, 0x31, 0x39, 0xeb, 0xe8, 0x04, 0xae, 0xae, 0xf2, 0x74, 0xd1,
	0xc5, 0xb1, 0xa3, 0x92, 0x37, 0xb5, 0xb9, 0x7b, 0x46, 0x7f, 0xbc, 0xfe, 0xf2, 0xc2, 0x1c, 0x87,
	0xfe, 0x1b, 0x1e, 0x3c, 0xfd, 0x78, 0xf7, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x4b, 0x24, 0xbf, 0xeb,
	0x32, 0x03, 0x00, 0x00,
}
