// Code generated by protoc-gen-go. DO NOT EDIT.
// source: signalcd/proto/types.proto

package signalcdproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DeploymentStatus_Phase int32

const (
	DeploymentStatus_DONTUSETHISVALUE DeploymentStatus_Phase = 0
	DeploymentStatus_UNKNOWN          DeploymentStatus_Phase = 1
	DeploymentStatus_SUCCESS          DeploymentStatus_Phase = 2
	DeploymentStatus_FAILURE          DeploymentStatus_Phase = 3
	DeploymentStatus_PROGRESS         DeploymentStatus_Phase = 4
	DeploymentStatus_PENDING          DeploymentStatus_Phase = 5
	DeploymentStatus_KILLED           DeploymentStatus_Phase = 6
)

var DeploymentStatus_Phase_name = map[int32]string{
	0: "DONTUSETHISVALUE",
	1: "UNKNOWN",
	2: "SUCCESS",
	3: "FAILURE",
	4: "PROGRESS",
	5: "PENDING",
	6: "KILLED",
}

var DeploymentStatus_Phase_value = map[string]int32{
	"DONTUSETHISVALUE": 0,
	"UNKNOWN":          1,
	"SUCCESS":          2,
	"FAILURE":          3,
	"PROGRESS":         4,
	"PENDING":          5,
	"KILLED":           6,
}

func (x DeploymentStatus_Phase) String() string {
	return proto.EnumName(DeploymentStatus_Phase_name, int32(x))
}

func (DeploymentStatus_Phase) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7c4df36a331e75e3, []int{1, 0}
}

type Deployment struct {
	Number               int64                `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	Created              *timestamp.Timestamp `protobuf:"bytes,2,opt,name=created,proto3" json:"created,omitempty"`
	Started              *timestamp.Timestamp `protobuf:"bytes,3,opt,name=started,proto3" json:"started,omitempty"`
	Finished             *timestamp.Timestamp `protobuf:"bytes,4,opt,name=finished,proto3" json:"finished,omitempty"`
	Status               *DeploymentStatus    `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Pipeline             *Pipeline            `protobuf:"bytes,6,opt,name=pipeline,proto3" json:"pipeline,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Deployment) Reset()         { *m = Deployment{} }
func (m *Deployment) String() string { return proto.CompactTextString(m) }
func (*Deployment) ProtoMessage()    {}
func (*Deployment) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c4df36a331e75e3, []int{0}
}

func (m *Deployment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Deployment.Unmarshal(m, b)
}
func (m *Deployment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Deployment.Marshal(b, m, deterministic)
}
func (m *Deployment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Deployment.Merge(m, src)
}
func (m *Deployment) XXX_Size() int {
	return xxx_messageInfo_Deployment.Size(m)
}
func (m *Deployment) XXX_DiscardUnknown() {
	xxx_messageInfo_Deployment.DiscardUnknown(m)
}

var xxx_messageInfo_Deployment proto.InternalMessageInfo

func (m *Deployment) GetNumber() int64 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *Deployment) GetCreated() *timestamp.Timestamp {
	if m != nil {
		return m.Created
	}
	return nil
}

func (m *Deployment) GetStarted() *timestamp.Timestamp {
	if m != nil {
		return m.Started
	}
	return nil
}

func (m *Deployment) GetFinished() *timestamp.Timestamp {
	if m != nil {
		return m.Finished
	}
	return nil
}

func (m *Deployment) GetStatus() *DeploymentStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *Deployment) GetPipeline() *Pipeline {
	if m != nil {
		return m.Pipeline
	}
	return nil
}

type DeploymentStatus struct {
	Phase                DeploymentStatus_Phase `protobuf:"varint,1,opt,name=phase,proto3,enum=signalcd.DeploymentStatus_Phase" json:"phase,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *DeploymentStatus) Reset()         { *m = DeploymentStatus{} }
func (m *DeploymentStatus) String() string { return proto.CompactTextString(m) }
func (*DeploymentStatus) ProtoMessage()    {}
func (*DeploymentStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c4df36a331e75e3, []int{1}
}

func (m *DeploymentStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeploymentStatus.Unmarshal(m, b)
}
func (m *DeploymentStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeploymentStatus.Marshal(b, m, deterministic)
}
func (m *DeploymentStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeploymentStatus.Merge(m, src)
}
func (m *DeploymentStatus) XXX_Size() int {
	return xxx_messageInfo_DeploymentStatus.Size(m)
}
func (m *DeploymentStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_DeploymentStatus.DiscardUnknown(m)
}

var xxx_messageInfo_DeploymentStatus proto.InternalMessageInfo

func (m *DeploymentStatus) GetPhase() DeploymentStatus_Phase {
	if m != nil {
		return m.Phase
	}
	return DeploymentStatus_DONTUSETHISVALUE
}

type Pipeline struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Created              *timestamp.Timestamp `protobuf:"bytes,3,opt,name=created,proto3" json:"created,omitempty"`
	Steps                []*Step              `protobuf:"bytes,4,rep,name=steps,proto3" json:"steps,omitempty"`
	Checks               []*Check             `protobuf:"bytes,5,rep,name=checks,proto3" json:"checks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Pipeline) Reset()         { *m = Pipeline{} }
func (m *Pipeline) String() string { return proto.CompactTextString(m) }
func (*Pipeline) ProtoMessage()    {}
func (*Pipeline) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c4df36a331e75e3, []int{2}
}

func (m *Pipeline) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pipeline.Unmarshal(m, b)
}
func (m *Pipeline) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pipeline.Marshal(b, m, deterministic)
}
func (m *Pipeline) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pipeline.Merge(m, src)
}
func (m *Pipeline) XXX_Size() int {
	return xxx_messageInfo_Pipeline.Size(m)
}
func (m *Pipeline) XXX_DiscardUnknown() {
	xxx_messageInfo_Pipeline.DiscardUnknown(m)
}

var xxx_messageInfo_Pipeline proto.InternalMessageInfo

func (m *Pipeline) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Pipeline) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Pipeline) GetCreated() *timestamp.Timestamp {
	if m != nil {
		return m.Created
	}
	return nil
}

func (m *Pipeline) GetSteps() []*Step {
	if m != nil {
		return m.Steps
	}
	return nil
}

func (m *Pipeline) GetChecks() []*Check {
	if m != nil {
		return m.Checks
	}
	return nil
}

type Step struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Image                string   `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	ImagePullSecrets     []string `protobuf:"bytes,3,rep,name=ImagePullSecrets,proto3" json:"ImagePullSecrets,omitempty"`
	Commands             []string `protobuf:"bytes,4,rep,name=commands,proto3" json:"commands,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Step) Reset()         { *m = Step{} }
func (m *Step) String() string { return proto.CompactTextString(m) }
func (*Step) ProtoMessage()    {}
func (*Step) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c4df36a331e75e3, []int{3}
}

func (m *Step) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Step.Unmarshal(m, b)
}
func (m *Step) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Step.Marshal(b, m, deterministic)
}
func (m *Step) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Step.Merge(m, src)
}
func (m *Step) XXX_Size() int {
	return xxx_messageInfo_Step.Size(m)
}
func (m *Step) XXX_DiscardUnknown() {
	xxx_messageInfo_Step.DiscardUnknown(m)
}

var xxx_messageInfo_Step proto.InternalMessageInfo

func (m *Step) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Step) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *Step) GetImagePullSecrets() []string {
	if m != nil {
		return m.ImagePullSecrets
	}
	return nil
}

func (m *Step) GetCommands() []string {
	if m != nil {
		return m.Commands
	}
	return nil
}

type Check struct {
	Name                 string             `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Image                string             `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	ImagePullSecrets     []string           `protobuf:"bytes,3,rep,name=ImagePullSecrets,proto3" json:"ImagePullSecrets,omitempty"`
	Duration             *duration.Duration `protobuf:"bytes,4,opt,name=duration,proto3" json:"duration,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Check) Reset()         { *m = Check{} }
func (m *Check) String() string { return proto.CompactTextString(m) }
func (*Check) ProtoMessage()    {}
func (*Check) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c4df36a331e75e3, []int{4}
}

func (m *Check) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Check.Unmarshal(m, b)
}
func (m *Check) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Check.Marshal(b, m, deterministic)
}
func (m *Check) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Check.Merge(m, src)
}
func (m *Check) XXX_Size() int {
	return xxx_messageInfo_Check.Size(m)
}
func (m *Check) XXX_DiscardUnknown() {
	xxx_messageInfo_Check.DiscardUnknown(m)
}

var xxx_messageInfo_Check proto.InternalMessageInfo

func (m *Check) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Check) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *Check) GetImagePullSecrets() []string {
	if m != nil {
		return m.ImagePullSecrets
	}
	return nil
}

func (m *Check) GetDuration() *duration.Duration {
	if m != nil {
		return m.Duration
	}
	return nil
}

func init() {
	proto.RegisterEnum("signalcd.DeploymentStatus_Phase", DeploymentStatus_Phase_name, DeploymentStatus_Phase_value)
	proto.RegisterType((*Deployment)(nil), "signalcd.Deployment")
	proto.RegisterType((*DeploymentStatus)(nil), "signalcd.DeploymentStatus")
	proto.RegisterType((*Pipeline)(nil), "signalcd.Pipeline")
	proto.RegisterType((*Step)(nil), "signalcd.Step")
	proto.RegisterType((*Check)(nil), "signalcd.Check")
}

func init() {
	proto.RegisterFile("signalcd/proto/types.proto", fileDescriptor_7c4df36a331e75e3)
}

var fileDescriptor_7c4df36a331e75e3 = []byte{
	// 521 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x93, 0x4f, 0x6f, 0xd3, 0x30,
	0x18, 0xc6, 0x49, 0xd3, 0x64, 0xe9, 0x3b, 0xe8, 0x22, 0x6b, 0x42, 0xa1, 0x07, 0xa8, 0x22, 0x24,
	0x2a, 0x0e, 0xa9, 0x54, 0x60, 0xf7, 0xd1, 0x86, 0x51, 0xad, 0x4a, 0x2b, 0xa7, 0x05, 0x89, 0x9b,
	0x97, 0x78, 0xad, 0xb5, 0xfc, 0x53, 0xec, 0x4a, 0xec, 0x7b, 0xf0, 0x31, 0xb8, 0x71, 0xe0, 0xeb,
	0x21, 0x3b, 0x7f, 0x3a, 0x6d, 0x42, 0xe3, 0xc2, 0xa9, 0x7e, 0xfd, 0xfc, 0x1e, 0xfb, 0xf1, 0xfb,
	0x36, 0x30, 0xe0, 0x6c, 0x9b, 0x91, 0x24, 0x8a, 0xc7, 0x45, 0x99, 0x8b, 0x7c, 0x2c, 0x6e, 0x0b,
	0xca, 0x3d, 0xb5, 0x46, 0x56, 0xa3, 0x0d, 0x5e, 0x6d, 0xf3, 0x7c, 0x9b, 0xd0, 0x8a, 0xb9, 0xda,
	0x5f, 0x8f, 0x05, 0x4b, 0x29, 0x17, 0x24, 0x2d, 0x2a, 0x74, 0xf0, 0xf2, 0x3e, 0x10, 0xef, 0x4b,
	0x22, 0x58, 0x9e, 0x55, 0xba, 0xfb, 0xb3, 0x03, 0x30, 0xa3, 0x45, 0x92, 0xdf, 0xa6, 0x34, 0x13,
	0xe8, 0x39, 0x98, 0xd9, 0x3e, 0xbd, 0xa2, 0xa5, 0xa3, 0x0d, 0xb5, 0x91, 0x8e, 0xeb, 0x0a, 0xbd,
	0x87, 0xa3, 0xa8, 0xa4, 0x44, 0xd0, 0xd8, 0xe9, 0x0c, 0xb5, 0xd1, 0xf1, 0x64, 0xe0, 0x55, 0x07,
	0x7b, 0xcd, 0xc1, 0xde, 0xba, 0xb9, 0x19, 0x37, 0xa8, 0x74, 0x71, 0x41, 0x4a, 0xe9, 0xd2, 0x1f,
	0x77, 0xd5, 0x28, 0x3a, 0x03, 0xeb, 0x9a, 0x65, 0x8c, 0xef, 0x68, 0xec, 0x74, 0x1f, 0xb5, 0xb5,
	0x2c, 0x9a, 0x80, 0xc9, 0x05, 0x11, 0x7b, 0xee, 0x18, 0xb5, 0xab, 0x69, 0x93, 0x77, 0x78, 0x61,
	0xa8, 0x08, 0x5c, 0x93, 0xc8, 0x03, 0xab, 0x60, 0x05, 0x4d, 0x58, 0x46, 0x1d, 0x53, 0xb9, 0xd0,
	0xc1, 0xb5, 0xaa, 0x15, 0xdc, 0x32, 0xee, 0x6f, 0x0d, 0xec, 0xfb, 0x87, 0xa1, 0x33, 0x30, 0x8a,
	0x1d, 0xe1, 0x54, 0xf5, 0xac, 0x3f, 0x19, 0xfe, 0xfd, 0x5e, 0x6f, 0x25, 0x39, 0x5c, 0xe1, 0xee,
	0x0d, 0x18, 0xaa, 0x46, 0xa7, 0x60, 0xcf, 0x96, 0xc1, 0x7a, 0x13, 0xfa, 0xeb, 0xcf, 0xf3, 0xf0,
	0xcb, 0xf9, 0x62, 0xe3, 0xdb, 0x4f, 0xd0, 0x31, 0x1c, 0x6d, 0x82, 0xcb, 0x60, 0xf9, 0x35, 0xb0,
	0x35, 0x59, 0x84, 0x9b, 0xe9, 0xd4, 0x0f, 0x43, 0xbb, 0x23, 0x8b, 0x4f, 0xe7, 0xf3, 0xc5, 0x06,
	0xfb, 0xb6, 0x8e, 0x9e, 0x82, 0xb5, 0xc2, 0xcb, 0x0b, 0x2c, 0xa5, 0xae, 0x94, 0x56, 0x7e, 0x30,
	0x9b, 0x07, 0x17, 0xb6, 0x81, 0x00, 0xcc, 0xcb, 0xf9, 0x62, 0xe1, 0xcf, 0x6c, 0xd3, 0xfd, 0xa5,
	0x81, 0xd5, 0x3c, 0x08, 0xf5, 0xa1, 0xc3, 0x62, 0x15, 0xb7, 0x87, 0x3b, 0x2c, 0x46, 0x08, 0xba,
	0x19, 0x49, 0xa9, 0x9a, 0x6d, 0x0f, 0xab, 0xf5, 0xdd, 0x91, 0xeb, 0xff, 0x3e, 0xf2, 0xd7, 0x60,
	0x70, 0x41, 0x0b, 0xee, 0x74, 0x87, 0xfa, 0xe8, 0x78, 0xd2, 0x3f, 0xf4, 0x22, 0x14, 0xb4, 0xc0,
	0x95, 0x88, 0xde, 0x80, 0x19, 0xed, 0x68, 0x74, 0x23, 0x47, 0x25, 0xb1, 0x93, 0x03, 0x36, 0x95,
	0xfb, 0xb8, 0x96, 0xdd, 0xef, 0xd0, 0x95, 0xbe, 0x36, 0xa0, 0x76, 0x27, 0xe0, 0x29, 0x18, 0x2c,
	0x25, 0xdb, 0x26, 0x75, 0x55, 0xa0, 0xb7, 0x60, 0xcf, 0xe5, 0x62, 0xb5, 0x4f, 0x92, 0x90, 0x46,
	0x25, 0x15, 0xdc, 0xd1, 0x87, 0xfa, 0xa8, 0x87, 0x1f, 0xec, 0xa3, 0x01, 0x58, 0x51, 0x9e, 0xa6,
	0x24, 0x8b, 0xab, 0xbc, 0x3d, 0xdc, 0xd6, 0xee, 0x0f, 0x0d, 0x0c, 0x95, 0xe5, 0x3f, 0xdd, 0xfd,
	0x01, 0xac, 0xe6, 0x53, 0xac, 0xff, 0xe5, 0x2f, 0x1e, 0xf4, 0x77, 0x56, 0x03, 0xb8, 0x45, 0x3f,
	0x9e, 0x7c, 0x7b, 0xd6, 0xb4, 0xaa, 0xc2, 0x4c, 0xf5, 0xf3, 0xee, 0x4f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xfd, 0x2b, 0x65, 0x8e, 0x30, 0x04, 0x00, 0x00,
}
