// Code generated by protoc-gen-go. DO NOT EDIT.
// source: signalcd/proto/ui.proto

package signalcdproto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListDeploymentRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListDeploymentRequest) Reset()         { *m = ListDeploymentRequest{} }
func (m *ListDeploymentRequest) String() string { return proto.CompactTextString(m) }
func (*ListDeploymentRequest) ProtoMessage()    {}
func (*ListDeploymentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_df79a9f155088a03, []int{0}
}

func (m *ListDeploymentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListDeploymentRequest.Unmarshal(m, b)
}
func (m *ListDeploymentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListDeploymentRequest.Marshal(b, m, deterministic)
}
func (m *ListDeploymentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListDeploymentRequest.Merge(m, src)
}
func (m *ListDeploymentRequest) XXX_Size() int {
	return xxx_messageInfo_ListDeploymentRequest.Size(m)
}
func (m *ListDeploymentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListDeploymentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListDeploymentRequest proto.InternalMessageInfo

type ListDeploymentResponse struct {
	Deployments          []*Deployment `protobuf:"bytes,1,rep,name=deployments,proto3" json:"deployments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ListDeploymentResponse) Reset()         { *m = ListDeploymentResponse{} }
func (m *ListDeploymentResponse) String() string { return proto.CompactTextString(m) }
func (*ListDeploymentResponse) ProtoMessage()    {}
func (*ListDeploymentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_df79a9f155088a03, []int{1}
}

func (m *ListDeploymentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListDeploymentResponse.Unmarshal(m, b)
}
func (m *ListDeploymentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListDeploymentResponse.Marshal(b, m, deterministic)
}
func (m *ListDeploymentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListDeploymentResponse.Merge(m, src)
}
func (m *ListDeploymentResponse) XXX_Size() int {
	return xxx_messageInfo_ListDeploymentResponse.Size(m)
}
func (m *ListDeploymentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListDeploymentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListDeploymentResponse proto.InternalMessageInfo

func (m *ListDeploymentResponse) GetDeployments() []*Deployment {
	if m != nil {
		return m.Deployments
	}
	return nil
}

type Deployment struct {
	Number               int64    `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Deployment) Reset()         { *m = Deployment{} }
func (m *Deployment) String() string { return proto.CompactTextString(m) }
func (*Deployment) ProtoMessage()    {}
func (*Deployment) Descriptor() ([]byte, []int) {
	return fileDescriptor_df79a9f155088a03, []int{2}
}

func (m *Deployment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Deployment.Unmarshal(m, b)
}
func (m *Deployment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Deployment.Marshal(b, m, deterministic)
}
func (m *Deployment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Deployment.Merge(m, src)
}
func (m *Deployment) XXX_Size() int {
	return xxx_messageInfo_Deployment.Size(m)
}
func (m *Deployment) XXX_DiscardUnknown() {
	xxx_messageInfo_Deployment.DiscardUnknown(m)
}

var xxx_messageInfo_Deployment proto.InternalMessageInfo

func (m *Deployment) GetNumber() int64 {
	if m != nil {
		return m.Number
	}
	return 0
}

func init() {
	proto.RegisterType((*ListDeploymentRequest)(nil), "signalcd.ListDeploymentRequest")
	proto.RegisterType((*ListDeploymentResponse)(nil), "signalcd.ListDeploymentResponse")
	proto.RegisterType((*Deployment)(nil), "signalcd.Deployment")
}

func init() { proto.RegisterFile("signalcd/proto/ui.proto", fileDescriptor_df79a9f155088a03) }

var fileDescriptor_df79a9f155088a03 = []byte{
	// 224 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2f, 0xce, 0x4c, 0xcf,
	0x4b, 0xcc, 0x49, 0x4e, 0xd1, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x2f, 0xcd, 0xd4, 0x03, 0x33,
	0x84, 0x38, 0x60, 0x12, 0x52, 0x32, 0xe9, 0xf9, 0xf9, 0xe9, 0x39, 0xa9, 0xfa, 0x89, 0x05, 0x99,
	0xfa, 0x89, 0x79, 0x79, 0xf9, 0x25, 0x89, 0x25, 0x99, 0xf9, 0x79, 0xc5, 0x10, 0x75, 0x4a, 0xe2,
	0x5c, 0xa2, 0x3e, 0x99, 0xc5, 0x25, 0x2e, 0xa9, 0x05, 0x39, 0xf9, 0x95, 0xb9, 0xa9, 0x79, 0x25,
	0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x4a, 0x01, 0x5c, 0x62, 0xe8, 0x12, 0xc5, 0x05, 0xf9,
	0x79, 0xc5, 0xa9, 0x42, 0x66, 0x5c, 0xdc, 0x29, 0x70, 0xd1, 0x62, 0x09, 0x46, 0x05, 0x66, 0x0d,
	0x6e, 0x23, 0x11, 0x3d, 0x98, 0x85, 0x7a, 0x48, 0x5a, 0x90, 0x15, 0x2a, 0xa9, 0x70, 0x71, 0x21,
	0xa4, 0x84, 0xc4, 0xb8, 0xd8, 0xf2, 0x4a, 0x73, 0x93, 0x52, 0x8b, 0x24, 0x18, 0x15, 0x18, 0x35,
	0x98, 0x83, 0xa0, 0x3c, 0xa3, 0x4a, 0x2e, 0xce, 0x50, 0xcf, 0xe0, 0xd4, 0xa2, 0xb2, 0xcc, 0xe4,
	0x54, 0xa1, 0x1c, 0x2e, 0x3e, 0x54, 0x47, 0x08, 0xc9, 0x23, 0xec, 0xc1, 0xea, 0x6e, 0x29, 0x05,
	0xdc, 0x0a, 0x20, 0xee, 0x57, 0x12, 0x6f, 0xba, 0xfc, 0x64, 0x32, 0x93, 0xa0, 0x12, 0xbf, 0x7e,
	0x99, 0xa1, 0x3e, 0x92, 0x03, 0x9d, 0xf8, 0xa3, 0x78, 0x61, 0x7a, 0xc1, 0x81, 0x93, 0xc4, 0x06,
	0xa6, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x60, 0xc9, 0x39, 0x93, 0x66, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UIServiceClient is the client API for UIService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UIServiceClient interface {
	ListDeployment(ctx context.Context, in *ListDeploymentRequest, opts ...grpc.CallOption) (*ListDeploymentResponse, error)
}

type uIServiceClient struct {
	cc *grpc.ClientConn
}

func NewUIServiceClient(cc *grpc.ClientConn) UIServiceClient {
	return &uIServiceClient{cc}
}

func (c *uIServiceClient) ListDeployment(ctx context.Context, in *ListDeploymentRequest, opts ...grpc.CallOption) (*ListDeploymentResponse, error) {
	out := new(ListDeploymentResponse)
	err := c.cc.Invoke(ctx, "/signalcd.UIService/ListDeployment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UIServiceServer is the server API for UIService service.
type UIServiceServer interface {
	ListDeployment(context.Context, *ListDeploymentRequest) (*ListDeploymentResponse, error)
}

// UnimplementedUIServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUIServiceServer struct {
}

func (*UnimplementedUIServiceServer) ListDeployment(ctx context.Context, req *ListDeploymentRequest) (*ListDeploymentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDeployment not implemented")
}

func RegisterUIServiceServer(s *grpc.Server, srv UIServiceServer) {
	s.RegisterService(&_UIService_serviceDesc, srv)
}

func _UIService_ListDeployment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDeploymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UIServiceServer).ListDeployment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/signalcd.UIService/ListDeployment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UIServiceServer).ListDeployment(ctx, req.(*ListDeploymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UIService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "signalcd.UIService",
	HandlerType: (*UIServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListDeployment",
			Handler:    _UIService_ListDeployment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "signalcd/proto/ui.proto",
}
