// Code generated by go-swagger; DO NOT EDIT.

package deployments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/signalcd/signalcd/cmd/agent/models"
)

// CurrentDeploymentReader is a Reader for the CurrentDeployment structure.
type CurrentDeploymentReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CurrentDeploymentReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewCurrentDeploymentOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCurrentDeploymentOK creates a CurrentDeploymentOK with default headers values
func NewCurrentDeploymentOK() *CurrentDeploymentOK {
	return &CurrentDeploymentOK{}
}

/*CurrentDeploymentOK handles this case with default header values.

OK
*/
type CurrentDeploymentOK struct {
	Payload *models.Deployment
}

func (o *CurrentDeploymentOK) Error() string {
	return fmt.Sprintf("[GET /deployments/current][%d] currentDeploymentOK  %+v", 200, o.Payload)
}

func (o *CurrentDeploymentOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Deployment)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
