// Code generated by go-swagger; DO NOT EDIT.

package deployments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewCurrentDeploymentParams creates a new CurrentDeploymentParams object
// with the default values initialized.
func NewCurrentDeploymentParams() *CurrentDeploymentParams {

	return &CurrentDeploymentParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCurrentDeploymentParamsWithTimeout creates a new CurrentDeploymentParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCurrentDeploymentParamsWithTimeout(timeout time.Duration) *CurrentDeploymentParams {

	return &CurrentDeploymentParams{

		timeout: timeout,
	}
}

// NewCurrentDeploymentParamsWithContext creates a new CurrentDeploymentParams object
// with the default values initialized, and the ability to set a context for a request
func NewCurrentDeploymentParamsWithContext(ctx context.Context) *CurrentDeploymentParams {

	return &CurrentDeploymentParams{

		Context: ctx,
	}
}

// NewCurrentDeploymentParamsWithHTTPClient creates a new CurrentDeploymentParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCurrentDeploymentParamsWithHTTPClient(client *http.Client) *CurrentDeploymentParams {

	return &CurrentDeploymentParams{
		HTTPClient: client,
	}
}

/*CurrentDeploymentParams contains all the parameters to send to the API endpoint
for the current deployment operation typically these are written to a http.Request
*/
type CurrentDeploymentParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the current deployment params
func (o *CurrentDeploymentParams) WithTimeout(timeout time.Duration) *CurrentDeploymentParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the current deployment params
func (o *CurrentDeploymentParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the current deployment params
func (o *CurrentDeploymentParams) WithContext(ctx context.Context) *CurrentDeploymentParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the current deployment params
func (o *CurrentDeploymentParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the current deployment params
func (o *CurrentDeploymentParams) WithHTTPClient(client *http.Client) *CurrentDeploymentParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the current deployment params
func (o *CurrentDeploymentParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *CurrentDeploymentParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
