// Code generated by go-swagger; DO NOT EDIT.

package deployments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/signalcd/signalcd/cmd/agent/models"
)

// SetCurrentDeploymentReader is a Reader for the SetCurrentDeployment structure.
type SetCurrentDeploymentReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SetCurrentDeploymentReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewSetCurrentDeploymentOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 500:
		result := NewSetCurrentDeploymentInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewSetCurrentDeploymentOK creates a SetCurrentDeploymentOK with default headers values
func NewSetCurrentDeploymentOK() *SetCurrentDeploymentOK {
	return &SetCurrentDeploymentOK{}
}

/*SetCurrentDeploymentOK handles this case with default header values.

OK
*/
type SetCurrentDeploymentOK struct {
	Payload *models.Deployment
}

func (o *SetCurrentDeploymentOK) Error() string {
	return fmt.Sprintf("[POST /deployments/current][%d] setCurrentDeploymentOK  %+v", 200, o.Payload)
}

func (o *SetCurrentDeploymentOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Deployment)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSetCurrentDeploymentInternalServerError creates a SetCurrentDeploymentInternalServerError with default headers values
func NewSetCurrentDeploymentInternalServerError() *SetCurrentDeploymentInternalServerError {
	return &SetCurrentDeploymentInternalServerError{}
}

/*SetCurrentDeploymentInternalServerError handles this case with default header values.

internal server error
*/
type SetCurrentDeploymentInternalServerError struct {
}

func (o *SetCurrentDeploymentInternalServerError) Error() string {
	return fmt.Sprintf("[POST /deployments/current][%d] setCurrentDeploymentInternalServerError ", 500)
}

func (o *SetCurrentDeploymentInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
