// Code generated by go-swagger; DO NOT EDIT.

package deployments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewSetCurrentDeploymentParams creates a new SetCurrentDeploymentParams object
// with the default values initialized.
func NewSetCurrentDeploymentParams() *SetCurrentDeploymentParams {
	var ()
	return &SetCurrentDeploymentParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSetCurrentDeploymentParamsWithTimeout creates a new SetCurrentDeploymentParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSetCurrentDeploymentParamsWithTimeout(timeout time.Duration) *SetCurrentDeploymentParams {
	var ()
	return &SetCurrentDeploymentParams{

		timeout: timeout,
	}
}

// NewSetCurrentDeploymentParamsWithContext creates a new SetCurrentDeploymentParams object
// with the default values initialized, and the ability to set a context for a request
func NewSetCurrentDeploymentParamsWithContext(ctx context.Context) *SetCurrentDeploymentParams {
	var ()
	return &SetCurrentDeploymentParams{

		Context: ctx,
	}
}

// NewSetCurrentDeploymentParamsWithHTTPClient creates a new SetCurrentDeploymentParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSetCurrentDeploymentParamsWithHTTPClient(client *http.Client) *SetCurrentDeploymentParams {
	var ()
	return &SetCurrentDeploymentParams{
		HTTPClient: client,
	}
}

/*SetCurrentDeploymentParams contains all the parameters to send to the API endpoint
for the set current deployment operation typically these are written to a http.Request
*/
type SetCurrentDeploymentParams struct {

	/*Pipeline*/
	Pipeline string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the set current deployment params
func (o *SetCurrentDeploymentParams) WithTimeout(timeout time.Duration) *SetCurrentDeploymentParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the set current deployment params
func (o *SetCurrentDeploymentParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the set current deployment params
func (o *SetCurrentDeploymentParams) WithContext(ctx context.Context) *SetCurrentDeploymentParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the set current deployment params
func (o *SetCurrentDeploymentParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the set current deployment params
func (o *SetCurrentDeploymentParams) WithHTTPClient(client *http.Client) *SetCurrentDeploymentParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the set current deployment params
func (o *SetCurrentDeploymentParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPipeline adds the pipeline to the set current deployment params
func (o *SetCurrentDeploymentParams) WithPipeline(pipeline string) *SetCurrentDeploymentParams {
	o.SetPipeline(pipeline)
	return o
}

// SetPipeline adds the pipeline to the set current deployment params
func (o *SetCurrentDeploymentParams) SetPipeline(pipeline string) {
	o.Pipeline = pipeline
}

// WriteToRequest writes these params to a swagger request
func (o *SetCurrentDeploymentParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param pipeline
	qrPipeline := o.Pipeline
	qPipeline := qrPipeline
	if qPipeline != "" {
		if err := r.SetQueryParam("pipeline", qPipeline); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
